# example netlify.toml
[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && pnpm build || npm run build"
  functions = "api"
  publish = "./build"

[build.environment]
  NPM_FLAGS="--version"

[context.production.environment]
  NODE_VERSION = '16.13.2'

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
